export default Ember.Object.extend({
  primaryStat: 'ethelo',
  resultSort: 'primary',
  showApprovalStat: false,
  showVoterPercentStat: false,
  showCalculations: false,
  showCriterionStats: false,
  showDissonanceStat: false,
  showEtheloStat: false,
  showHistogramChart: false,
  showOnlyVoted: false,
  showOptionCategoryStats: false,
  showOptionCategoryTitles: false,
  showOptionStats: false,
  showPeopleChart: false,
  showScenarioStats: false,
  showSupportStat: false,
  showTotalVotesStat: false,
  showDistributionChart: false,
  showMetricsChart: false,
  showBarChart: false,
});
